# .bashrc
# User specific aliases and functions
alias rm='rm -i'alias cp='cp -i'alias mv='mv -i'
# Source global definitionsif [ -f /etc/bashrc ]; then	. /etc/bashrcfi
export PATH=$PATH:/usr/local/bin

cowsay "Sigh...!"
